### ISSUE TITLE
Логика игры

### ISSUE THREAD

**Issue by MyDanielM** [MyDanielM/trpoLab7#7]
Изучить [макет](https://github.com/MyDanielM/trpoLab7/issues/4), продумать алгоритм "переключения" вопросов, подсчёт очков, алгоритм проверки на правильность ответа. 
Результат оформить в виде папки со скриптами в репозитории.

**Comment by RyjkovAlexey** [comment]
Алгоритм переключения вопрос написал, подсчет очков реализовал, проверку на правильность так же сделал
