### ISSUE TITLE
Постер для игры

### ISSUE THREAD

**Issue by MyDanielM** [MyDanielM/trpoLab7#8]
Нарисовать рекламный постер для игры.
Размеры: 1080х1080px.
Контент: Связанный с контекстом игры.
Использовать уже известные технологии.
Суть постера - привлечь новых пользователей в игру.
Результат работы оформить в виде .jpg файла в репозитории.

**Comment by Dasshaaa** [comment]
![Без названия, копия (11)](https://user-images.githubusercontent.com/63259368/83027792-37532f80-a039-11ea-99cc-b967b3e2773f.jpg)
